spring:
  application:
    name: aims-bulk-service
  cloud:
    gcp:
      project-id: PROJECT_ID_HERE_MUST_BE_SUPPLIED
      bigquery:
        dataset-name: bulk_status      
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 25MB
  thymeleaf:
    reactive:
      max-chunk-size: 8192
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
logging:
  level:
    root: INFO
    uk:
      gov:
        ons: INFO
    reactor:
      netty: INFO
aims:
  bigquery:
    info-table: bulkinfo
  cloud-functions:
    create-cloud-task-function: https://europe-west2-ons-aims-initial-test.cloudfunctions.net/create-cloud-task-function  