spring:
  application:
    name: aims-bulk-service
  cloud:
    gcp:
      project-id: YOUR-GCP-PROJECT-ID-HERE
      bigquery:
        dataset-name: bulk_status
      sql:
        database-name: bulk-status-db
        instance-connection-name: YOUR-GCP-PROJECT-ID-HERE:europe-west2:bulk-status-instance
  codec:
    max-in-memory-size: 10MB
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 25MB
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  sql:
    init:
      continue-on-error: true
      mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    username: YOUR-DATABASE-USER
    password: YOUR-DATABASE-PASSWORD
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
logging:
  level:
    root: INFO
    uk:
      gov:
        ons: DEBUG
    reactor:
      netty: INFO
aims:
  cloud-functions:
    create-cloud-task-function: https://europe-west2-YOUR-GCP-PROJECT-ID-HERE.cloudfunctions.net/create-cloud-task-function
    create-signed-url-function: https://europe-west2-YOUR-GCP-PROJECT-ID-HERE.cloudfunctions.net/create-signed-url-function
  project-number: YOUR-GCP-PROJECT-NUMBER-HERE
  epochs: 93|91|89
  current-epoch: 93
  # Update the records processed at every n% of completion
  report-frequency: 5
ids:
  cloud:
    gcp:
      project-id: ons-aims-ids-test
  pubsub:
    subscription-new-ids-job: ids-table-available
    subscription-download-complete: aims-remove-table
async:
  executor:
    thread:
      core_pool_size: 5
      # Configure the maximum number of threads
      max_pool_size: 5
      # Configure queue size
      queue_capacity: 999
      # Configure the maximum idle time of threads
      keep_alive_seconds: 60
      # Configure the name prefix of threads in the thread pool
      name:
        prefix: bulk-async-