CREATE TABLE bulkinfo (
  runid INT NOT NULL AUTO_INCREMENT,
  userid VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  totalrecs INT NOT NULL,
  recssofar INT NOT NULL,
  startdate DATETIME DEFAULT CURRENT_TIMESTAMP,
  enddate DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (runid));