CREATE TABLE bulkinfo (
  jobid INT NOT NULL AUTO_INCREMENT,
  userid VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  totalrecs INT NOT NULL,
  recssofar INT NOT NULL,
  startdate DATETIME DEFAULT CURRENT_TIMESTAMP,
  enddate DATETIME ON UPDATE CURRENT_TIMESTAMP,
  dataset VARCHAR(255),
  topic VARCHAR(255),
  uimetadata TEXT,
  PRIMARY KEY (jobid));
  
CREATE TABLE ids_bulkinfo (
  jobid INT NOT NULL AUTO_INCREMENT,
  idsjobid VARCHAR(255) NOT NULL,
  userid VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  totalrecs INT NOT NULL,
  recssofar INT NOT NULL,
  startdate DATETIME DEFAULT CURRENT_TIMESTAMP,
  enddate DATETIME ON UPDATE CURRENT_TIMESTAMP,
  dataset VARCHAR(255),
  topic VARCHAR(255),
  uimetadata TEXT,
  test BOOLEAN,
  PRIMARY KEY (jobid));